/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "agenda.h"
#include <string.h>
#include <stdio.h>

FILE *file;
char fileName[100];
int size;

struct contact *loadFile(){
    struct contact *contacts;
    int i;

    if((file = fopen(fileName,"ab+"))==NULL){
        printf("Error: File %s not open.\n",fileName);
        exit(0);
    }

    fseek(file,0,SEEK_END);
    size = ftell(file)/sizeof(struct contact);
    fseek(file,0,SEEK_SET);

    contacts =(struct contact *) malloc(sizeof(struct contact)*size);
    for(i=0;i<size;i++){
        fread(&contacts[i],sizeof(struct contact),1,file);
    }

    fclose(file);
    return contacts;
}

struct contact search(char *name){
    int i;
    struct contact *contacts;
    contacts = loadFile();
    i=0;
    while(i<size && strcmp(name,contacts[i].name)!=0) i++;
    if(i< size) return contacts[i];
    struct contact cont;
    memset(&cont, 0, sizeof(struct contact));
    return  cont;
}

int *
insertcontact_1_svc(struct contact *argp, struct svc_req *rqstp)
{
    static int  result;

    int i, included = 0;
    struct contact *contacts;
    contacts = loadFile();

    if((file = fopen(fileName,"wb"))==NULL){
        printf("Error: File %s not open.\n",fileName);
        return &result;
        //exit(0);
    }

    i=0;
    while(i<size && strcmp(argp->name,contacts[i].name)>0){
        fwrite(&contacts[i],1,sizeof(struct contact),file);
        i++;
    }
    if(strcmp(argp->name,contacts[i].name)!=0){
        fwrite(argp,1,sizeof(struct contact),file);
        included = 1;
    }
    while(i<size){
        fwrite(&contacts[i],1,sizeof(struct contact),file);
        i++;
    }

    fclose(file);
    result = included;

    return &result;
}

struct contact *
searchcontact_1_svc(char **argp, struct svc_req *rqstp)
{
    static struct contact  result;
    int i;
    struct contact *contacts;
    contacts = loadFile();
    i=0;
    while(i<size && strcmp(*argp,contacts[i].name)!=0) i++;
    if(i< size){ 
//        result = (struct contact *) malloc(sizeof(struct contact));
        result = contacts[i];
    }
    else memset(&result, 0, sizeof(struct contact));

    return &result;
}

int *
removecontact_1_svc(char **argp, struct svc_req *rqstp)
{
    static int  result;
    int i, deleted = 0;
    struct contact contactRemove;
    contactRemove = search(*argp);
    if(strcmp(contactRemove.name,"")){
        struct contact *contacts;
        contacts = loadFile();

        if((file = fopen(fileName,"wb"))==NULL){
            printf("Error: File %s not open.\n",fileName);
            exit(0);
        }
        i=0;
        while(i<size && strcmp(contactRemove.name,contacts[i].name)>0){
            fwrite(&contacts[i],1,sizeof(struct contact),file);
            i++;
        }
        i++;
        while(i<size){
            fwrite(&contacts[i],1,sizeof(struct contact),file);
            i++;
        }
        fclose(file);
        deleted = 1;
    }
    result = deleted;
    return &result;
}

void *
setfile_1_svc(char **argp, struct svc_req *rqstp)
{
    static char * result;
    strcpy(fileName,*argp);
    return (void *) &result;
}
