/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AGENDA_H_RPCGEN
#define _AGENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct contact {
	char name[50];
	char fone[15];
	char address[50];
};
typedef struct contact contact;

#define agenda 0x20000000
#define agenda 1

#if defined(__STDC__) || defined(__cplusplus)
#define insertContact 1
extern  int * insertcontact_1(struct contact *, CLIENT *);
extern  int * insertcontact_1_svc(struct contact *, struct svc_req *);
#define searchContact 2
extern  struct contact * searchcontact_1(char **, CLIENT *);
extern  struct contact * searchcontact_1_svc(char **, struct svc_req *);
#define removeContact 3
extern  int * removecontact_1(char **, CLIENT *);
extern  int * removecontact_1_svc(char **, struct svc_req *);
#define setFile 4
extern  void * setfile_1(char **, CLIENT *);
extern  void * setfile_1_svc(char **, struct svc_req *);
extern int agenda_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define insertContact 1
extern  int * insertcontact_1();
extern  int * insertcontact_1_svc();
#define searchContact 2
extern  struct contact * searchcontact_1();
extern  struct contact * searchcontact_1_svc();
#define removeContact 3
extern  int * removecontact_1();
extern  int * removecontact_1_svc();
#define setFile 4
extern  void * setfile_1();
extern  void * setfile_1_svc();
extern int agenda_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_contact (XDR *, contact*);

#else /* K&R C */
extern bool_t xdr_contact ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AGENDA_H_RPCGEN */
